#!/bin/bash

run(){
    roslaunch starter starter.launch
}

test_dev(){
    roslaunch starter starter_test.launch
}

test_bag(){
    (roscore &)
    rosbag play $1
}

build(){
    rm -rf devel/ build/
    catkin_make -DPYTHON_EXECUTABLE=/usr/bin/python3
}


case $1 in
    "build")
        build
    ;;
    "test")
        test_dev
    ;;
    "testd")
        test_bag $2
    ;;
    *)
        run
    ;;
esac
