#!/bin/bash

run(){
    roslaunch test_tools visual_mark_object_lane.launch
}

build(){
    rm -rf devel/ build/
    catkin_make -DPYTHON_EXECUTABLE=/usr/bin/python3
}


case $1 in
    "build")
        build
    ;;
    "env")
        env
    ;;
    "test")
        test_func
    ;;
    *)
        run
    ;;
esac
