#!/bin/bash

run(){
    roslaunch starter starter.launch
}

build(){
    rm -rf devel/ build/
    catkin_make -DPYTHON_EXECUTABLE=/usr/bin/python3
}


case $1 in
    "build")
        build
    ;;
    *)
        run
    ;;
esac
