#!/bin/bash

env(){
    export ROS_PYTHON_VERSION=3
    OTHER_ENV=/home/nevc/gitlab/swucar/other/devel/setup.bash
    if [ -f "${OTHER_ENV}" ];then
        source /home/nevc/gitlab/swucar/other/devel/setup.bash
    else
        echo "${OTHER_ENV} not exist!"
        exit 1
    fi
}

run(){
    roslaunch starter starter.launch
}

test_func(){
    roslaunch test_tools fake_starter.launch
}

build(){
    rm -rf devel/ build/
    catkin_make -DPYTHON_EXECUTABLE=/usr/bin/python3
}


case $1 in
    "build")
        build
    ;;
    "env")
        env
    ;;
    "test")
        test_func
    ;;
    *)
        run
    ;;
esac
